/** TheMealDB'nin tüm malzeme kataloğu (list.php?i=list) — sadece gerçekten
 * yüklenen fotoğrafı olanlar (967/992, kontrol edildi). GROQ_API_KEY bu
 * ortamda tanımlı olmadığı için toplu AI çevirisi yerine elle, en yaygın/
 * tanınabilir malzemeler için Türkçe etiket eklendi; çok niş/bölgesel/marka
 * isimleri (ör. "Doubanjiang", "Sirop De Liège") için karşılık yoksa
 * getIngredientLabel orijinal İngilizce adı döner (bkz. categoryMeta.ts'teki
 * aynı desen). */
export const INGREDIENT_LABELS_TR: Record<string, string> = {
  "Achiote Paste": "Achiote Ezmesi",
  "Achiote Seeds": "Achiote Tohumu",
  "Alinos Sauce": "Alinos Sosu",
  "All purpose flour": "Un (çok amaçlı)",
  "All-purpose Seasoning": "Çok Amaçlı Baharat Karışımı",
  Allspice: "Yenibahar",
  "Allspice Berries": "Yenibahar Tanesi",
  "Almond Essence": "Badem Esansı",
  "Almond Extract": "Badem Özütü",
  "Almond Flour": "Badem Unu",
  "Almond Milk": "Badem Sütü",
  "Almond Paste": "Badem Ezmesi",
  Almonds: "Badem",
  "Ancho Chillies": "Ancho Biberi",
  "Anchovy Fillet": "Hamsi Fileto",
  "Apple Cider Vinegar": "Elma Sirkesi",
  Apples: "Elma",
  Apricot: "Kayısı",
  "Apricot Jam": "Kayısı Reçeli",
  "Arabic Rice": "Arap Pilavı Pirinci",
  Asparagus: "Kuşkonmaz",
  Aubergine: "Patlıcan",
  Avocado: "Avokado",
  "Baby Aubergine": "Mini Patlıcan",
  "Baby Lettuce Leaves": "Mini Marul Yaprağı",
  "Baby New Potatoes": "Yeni Küçük Patates",
  "Baby Plum Tomatoes": "Mini Domates",
  "Baby Squid": "Mini Kalamar",
  Bacon: "Domuz Pastırması",
  Baguette: "Baget Ekmek",
  "Baked Beans": "Fırında Kuru Fasulye",
  "Baking Powder": "Kabartma Tozu",
  "Balsamic Vinegar": "Balzamik Sirke",
  "Bamboo Shoot": "Bambu Filizi",
  Banana: "Muz",
  "Banana Leaves": "Muz Yaprağı",
  "Banana Pepper": "Sivri Biber",
  "Barbeque Sauce": "Barbekü Sosu",
  Basil: "Fesleğen",
  "Basil Leaves": "Fesleğen Yaprağı",
  "Basmati Rice": "Basmati Pirinç",
  "Bay Leaf": "Defne Yaprağı",
  "Bay Leaves": "Defne Yaprağı",
  "Bean Sprouts": "Fasulye Filizi",
  Beef: "Dana Eti",
  "Beef Brisket": "Dana Döş",
  "Beef Cutlet": "Dana Şinitzel",
  "Beef Fillet": "Dana Bonfile",
  "Beef Flank Steak": "Dana Bohça Eti",
  "Beef Gravy": "Dana Sosu",
  "Beef Kidney": "Dana Böbreği",
  "Beef Shin": "Dana İncik",
  "Beef Shoulder": "Dana Kürek",
  "Beef Stock": "Dana Suyu",
  "Beef Stock Concentrate": "Dana Suyu Konsantresi",
  "Beef Stock Cubes": "Dana Bulyon Küpü",
  "Beef tomatoes": "İri Domates",
  Beer: "Bira",
  Beetroot: "Pancar",
  Beets: "Pancar",
  "Bicarbonate Of Soda": "Karbonat",
  "Birds-eye Chillies": "Acı Kuş Biberi",
  "Black Beans": "Siyah Fasulye",
  "Black Cardamom Pods": "Kara Kakule",
  "Black Eyed Peas": "Börülce",
  "Black Olives": "Siyah Zeytin",
  "Black Pepper": "Karabiber",
  "Black Pudding": "Kan Sosisi",
  Blackberries: "Böğürtlen",
  Blueberries: "Yaban Mersini",
  "Boiling Water": "Kaynar Su",
  "Borlotti Beans": "Barbunya Fasulye",
  Brandy: "Brendi",
  Bread: "Ekmek",
  "Bread Flour": "Ekmeklik Un",
  "Bread Rolls": "Ekmek Çörekleri",
  Breadcrumbs: "Galeta Unu",
  Brie: "Brie Peyniri",
  "Broad Beans": "Bakla",
  Broccoli: "Brokoli",
  "Brown Lentils": "Kahverengi Mercimek",
  "Brown Rice": "Esmer Pirinç",
  "Brown Sugar": "Esmer Şeker",
  "Brussels Sprouts": "Brüksel Lahanası",
  Buckwheat: "Karabuğday",
  "Buckwheat Flour": "Karabuğday Unu",
  "Bulgur Wheat": "Bulgur",
  Bun: "Burger Ekmeği",
  Buns: "Burger Ekmeği",
  Butter: "Tereyağı",
  "Butter Beans": "İri Fasulye",
  Buttermilk: "Ayran (yayık)",
  "Butternut Squash": "Bal Kabağı",
  Cabbage: "Lahana",
  "Cabbage Leaves": "Lahana Yaprağı",
  Cacao: "Kakao Çekirdeği",
  Cajun: "Cajun Baharatı",
  Capers: "Kapari",
  Caramel: "Karamel",
  "Caramel Sauce": "Karamel Sos",
  Cardamom: "Kakule",
  Carrots: "Havuç",
  "Cashew Nuts": "Kaju",
  Cashews: "Kaju",
  Cassava: "Manyok",
  "Caster Sugar": "İnce Toz Şeker",
  "Cayenne Pepper": "Kayen Biberi",
  Celeriac: "Kereviz Kökü",
  Celery: "Kereviz",
  "Cheddar Cheese": "Cheddar Peyniri",
  Cheese: "Peynir",
  Cherry: "Kiraz",
  "Cherry Tomatoes": "Kiraz Domates",
  Chestnuts: "Kestane",
  Chicken: "Tavuk",
  "Chicken Breast": "Tavuk Göğsü",
  "Chicken Breasts": "Tavuk Göğsü",
  "Chicken Legs": "Tavuk But",
  "Chicken Liver": "Tavuk Ciğeri",
  "Chicken Stock": "Tavuk Suyu",
  "Chicken Stock Cube": "Tavuk Bulyon Küpü",
  "Chicken Thighs": "Tavuk But",
  "Chicken Wings": "Tavuk Kanat",
  "Chicken drumsticks": "Tavuk Baget",
  "Chickpea Flour": "Nohut Unu",
  Chickpeas: "Nohut",
  "Chili Powder": "Acı Biber Tozu",
  Chilli: "Acı Biber",
  "Chilli Flakes": "Pul Biber",
  "Chilli Powder": "Acı Biber Tozu",
  "Chilli Sauce": "Acı Biber Sosu",
  Chives: "Kıvırcık Soğan (frenk soğanı)",
  "Chocolate Chips": "Çikolata Parçacığı",
  "Chopped Onion": "Doğranmış Soğan",
  "Chopped Parsley": "Doğranmış Maydanoz",
  "Chopped Tomatoes": "Doğranmış Domates",
  Chorizo: "Chorizo Sosis",
  Cider: "Elma Şarabı",
  "Cider Vinegar": "Elma Sirkesi",
  Cilantro: "Kişniş",
  "Cilantro Leaves": "Kişniş Yaprağı",
  Cinnamon: "Tarçın",
  "Cinnamon Stick": "Tarçın Çubuğu",
  Clams: "Midye (küçük deniz tarağı)",
  "Clear Honey": "Sıvı Bal",
  Cloves: "Karanfil",
  Cocoa: "Kakao",
  "Cocoa Powder": "Kakao Tozu",
  "Coconut Cream": "Hindistan Cevizi Kreması",
  "Coconut Flakes": "Hindistan Cevizi Rendesi",
  "Coconut Milk": "Hindistan Cevizi Sütü",
  "Coconut Oil": "Hindistan Cevizi Yağı",
  Cod: "Morina Balığı",
  "Cold Water": "Soğuk Su",
  "Condensed Milk": "Yoğunlaştırılmış Süt (kondense süt)",
  Coriander: "Kişniş",
  "Coriander Leaves": "Kişniş Yaprağı",
  "Coriander Seeds": "Kişniş Tohumu",
  "Corn Flour": "Mısır Unu",
  "Corn On The Cob": "Mısır Koçanı",
  "Corn Tortillas": "Mısır Tortillası",
  "Corned Beef": "Konserve Dana Eti",
  Cornmeal: "Mısır Unu (kaba)",
  Cornstarch: "Mısır Nişastası",
  "Cottage Cheese": "Lor Peyniri",
  Courgettes: "Kabak",
  Couscous: "Kuskus",
  Cranberry: "Kızılcık",
  Cream: "Krema",
  "Cream Cheese": "Krem Peynir",
  "Creamed Corn": "Ezme Mısır",
  Cucumber: "Salatalık",
  Cumin: "Kimyon",
  "Cumin Seeds": "Kimyon Tohumu",
  Currants: "Kuş Üzümü",
  "Curry Powder": "Köri Tozu",
  Custard: "Muhallebi (custard)",
  "Daikon Radish": "Turp (daikon)",
  "Dark Chocolate": "Bitter Çikolata",
  "Dark Rum": "Koyu Rom",
  "Dark Soy Sauce": "Koyu Soya Sosu",
  Dates: "Hurma",
  "Deli Ham": "Jambon",
  "Demerara Sugar": "Demerara Şekeri",
  "Desiccated Coconut": "Rendelenmiş Hindistan Cevizi",
  "Dijon Mustard": "Dijon Hardalı",
  Dill: "Dereotu",
  "Dill Pickles": "Turşu Salatalık",
  "Double Cream": "Yoğun Krema",
  "Dried Apricots": "Kuru Kayısı",
  "Dried Cherries": "Kuru Kiraz",
  "Dried Chillies": "Kuru Acı Biber",
  "Dried Dill": "Kuru Dereotu",
  "Dried Mint": "Kuru Nane",
  "Dried Oregano": "Kuru Kekik",
  "Dried Red Chillies": "Kuru Kırmızı Biber",
  "Dried Shrimp": "Kuru Karides",
  "Dry White Wine": "Sek Beyaz Şarap",
  Duck: "Ördek",
  "Duck Fat": "Ördek Yağı",
  "Duck Legs": "Ördek But",
  Egg: "Yumurta",
  "Egg Noodles": "Yumurtalı Erişte",
  "Egg White": "Yumurta Beyazı",
  "Egg Yolks": "Yumurta Sarısı",
  Eggs: "Yumurta",
  "Evaporated Milk": "Buharlaştırılmış Süt",
  "Extra Virgin Olive Oil": "Sızma Zeytinyağı",
  Fennel: "Rezene",
  "Fennel Bulb": "Rezene Kökü",
  "Fennel Seeds": "Rezene Tohumu",
  Fenugreek: "Çemen Otu",
  Feta: "Beyaz Peynir",
  Figs: "İncir",
  "Fillet Of Steak": "Bonfile",
  "Filo Pastry": "Yufka (filo)",
  "Fish Sauce": "Balık Sosu",
  "Fish Stock": "Balık Suyu",
  "Fish fillet": "Balık Fileto",
  "Flaked Almonds": "Yaprak Badem",
  "Flank Steak": "Bohça Eti",
  Flour: "Un",
  "Flour Tortilla": "Buğday Tortillası",
  "Fresh Basil": "Taze Fesleğen",
  "Fresh Thyme": "Taze Kekik",
  "Freshly Chopped Parsley": "Taze Doğranmış Maydanoz",
  "Frozen Peas": "Dondurulmuş Bezelye",
  "Full Fat Yogurt": "Tam Yağlı Yoğurt",
  "Garam Masala": "Garam Masala",
  Garlic: "Sarımsak",
  "Garlic Clove": "Sarımsak Dişi",
  "Garlic Powder": "Sarımsak Tozu",
  Ghee: "Sadeyağ (ghee)",
  Ginger: "Zencefil",
  "Goat Meat": "Keçi Eti",
  "Goats Cheese": "Keçi Peyniri",
  "Golden Syrup": "Altın Şurup",
  "Goose Fat": "Kaz Yağı",
  "Gouda Cheese": "Gouda Peyniri",
  "Granulated Sugar": "Toz Şeker",
  "Grape Tomatoes": "Salkım Domates",
  Grapefruit: "Greyfurt",
  "Greek Yogurt": "Süzme Yoğurt",
  "Green Beans": "Taze Fasulye",
  "Green Chilli": "Yeşil Acı Biber",
  "Green Olives": "Yeşil Zeytin",
  "Green Pepper": "Yeşil Biber",
  Grits: "Mısır Lapası (grits)",
  "Ground Almonds": "Toz Badem",
  "Ground Beef": "Kıyma (dana)",
  "Ground Black Pepper": "Çekilmiş Karabiber",
  "Ground Chicken": "Tavuk Kıyma",
  "Ground Cinnamon": "Toz Tarçın",
  "Ground Clove": "Toz Karanfil",
  "Ground Coriander": "Toz Kişniş",
  "Ground Cumin": "Toz Kimyon",
  "Ground Ginger": "Toz Zencefil",
  "Ground Nutmeg": "Toz Muskat",
  "Ground Pork": "Domuz Kıyma",
  "Ground Turmeric": "Toz Zerdeçal",
  "Ground Walnuts": "Toz Ceviz",
  Haddock: "Mezgit Balığı",
  Ham: "Jambon",
  "Haricot Beans": "Kuru Fasulye",
  Hazlenuts: "Fındık",
  "Heavy Cream": "Yoğun Krema",
  Herring: "Ringa Balığı",
  Honey: "Bal",
  Horseradish: "Yaban Turpu",
  Hummus: "Humus",
  "Ice Cream": "Dondurma",
  "Ice Cubes": "Buz Küpü",
  "Iceberg Lettuce": "Aysberg Marul",
  "Icing Sugar": "Pudra Şekeri",
  Jalapeno: "Jalapeno Biberi",
  Jam: "Reçel",
  "Jasmine Rice": "Yasemin Pirinci",
  Kale: "Kara Lahana",
  "Kidney Beans": "Kuru Fasulye (kırmızı)",
  "King Prawns": "İri Karides",
  "Kosher Salt": "Kaya Tuzu",
  Lamb: "Kuzu Eti",
  "Lamb Leg": "Kuzu But",
  "Lamb Mince": "Kuzu Kıyma",
  "Lamb Shanks": "Kuzu İncik",
  "Lamb Shoulder": "Kuzu Kürek",
  Lard: "Domuz Yağı",
  Leek: "Pırasa",
  Lemon: "Limon",
  "Lemon Juice": "Limon Suyu",
  "Lemon Zest": "Limon Kabuğu Rendesi",
  Lemongrass: "Limon Otu",
  Lemons: "Limon",
  Lentils: "Mercimek",
  Lettuce: "Marul",
  "Light Rum": "Beyaz Rom",
  "Lima Beans": "Bakla (lima)",
  Lime: "Misket Limonu",
  "Lime Leaves": "Misket Limonu Yaprağı",
  "Lime juice": "Misket Limonu Suyu",
  Lobster: "Istakoz",
  Macaroni: "Makarna (kısa)",
  Mackerel: "Uskumru",
  "Malt Vinegar": "Malt Sirkesi",
  Mango: "Mango",
  "Maple Syrup": "Akçaağaç Şurubu",
  Marjoram: "Mercanköşk",
  Mascarpone: "Mascarpone Peyniri",
  Mayonnaise: "Mayonez",
  "Melted Butter": "Eritilmiş Tereyağı",
  Milk: "Süt",
  "Milk Chocolate": "Sütlü Çikolata",
  "Minced Beef": "Dana Kıyma",
  "Minced Garlic": "Sarımsak Ezmesi",
  "Minced Pork": "Domuz Kıyma",
  Mint: "Nane",
  "Mixed peppers": "Karışık Biber",
  Molasses: "Pekmez",
  Monkfish: "Fener Balığı",
  Mozzarella: "Mozzarella Peyniri",
  Mushrooms: "Mantar",
  Mussels: "Midye",
  Mustard: "Hardal",
  "Mustard Powder": "Hardal Tozu",
  "Mustard Seeds": "Hardal Tohumu",
  "Naan Bread": "Naan Ekmeği",
  "Natural Yoghurt": "Sade Yoğurt",
  "New Potatoes": "Yeni Patates",
  Noodles: "Erişte / Noodle",
  Nutmeg: "Muskat",
  Oatmeal: "Yulaf Ezmesi",
  Oats: "Yulaf",
  Oil: "Yağ",
  "Olive Oil": "Zeytinyağı",
  Onion: "Soğan",
  Onions: "Soğan",
  Orange: "Portakal",
  "Orange Juice": "Portakal Suyu",
  "Orange Zest": "Portakal Kabuğu Rendesi",
  Oregano: "Kekik",
  Oxtail: "Kuyruk Eti (öküz kuyruğu)",
  "Oyster Mushrooms": "İstiridye Mantarı",
  "Oyster Sauce": "İstiridye Sosu",
  Oysters: "İstiridye",
  Paneer: "Paneer Peyniri",
  Paprika: "Kırmızı Toz Biber",
  "Parma Ham": "Parma Jambonu",
  Parmesan: "Parmesan Peyniri",
  "Parmesan Cheese": "Parmesan Peyniri",
  Parsley: "Maydanoz",
  Parsnips: "Yaban Havucu",
  Passata: "Domates Sosu (passata)",
  Peaches: "Şeftali",
  "Peanut Butter": "Fıstık Ezmesi",
  "Peanut Oil": "Yer Fıstığı Yağı",
  Peanuts: "Yer Fıstığı",
  Pears: "Armut",
  Peas: "Bezelye",
  "Pecan Nuts": "Pekan Cevizi",
  Penne: "Penne Makarna",
  "Penne Pasta": "Penne Makarna",
  Pepper: "Biber",
  Peppercorns: "Karabiber Tanesi",
  Pineapple: "Ananas",
  "Pineapple Juice": "Ananas Suyu",
  "Pinto Beans": "Barbunya",
  Pistachio: "Antep Fıstığı",
  "Pita Bread": "Pide / Pita Ekmeği",
  "Plain Chocolate": "Bitter Çikolata",
  "Plain Flour": "Sade Un",
  "Plum Tomatoes": "Salça Domatesi",
  Pomegranate: "Nar",
  "Poppy Seeds": "Haşhaş Tohumu",
  Pork: "Domuz Eti",
  "Pork Chops": "Domuz Pirzola",
  "Pork Shoulder": "Domuz Kürek",
  "Pork Tenderloin": "Domuz Bonfile",
  "Potato Starch": "Patates Nişastası",
  Potatoes: "Patates",
  "Powdered Sugar": "Pudra Şekeri",
  Prawns: "Karides",
  Prosciutto: "Prosciutto (İtalyan jambonu)",
  Prunes: "Kuru Erik",
  "Puff Pastry": "Milföy Hamuru",
  Pumpkin: "Balkabağı",
  Quinoa: "Kinoa",
  Radish: "Turp",
  Raisins: "Kuru Üzüm",
  Raspberries: "Ahududu",
  "Red Cabbage": "Kırmızı Lahana",
  "Red Chilli": "Kırmızı Acı Biber",
  "Red Onions": "Kırmızı Soğan",
  "Red Pepper": "Kırmızı Biber",
  "Red Wine": "Kırmızı Şarap",
  "Red Wine Vinegar": "Kırmızı Şarap Sirkesi",
  Rice: "Pirinç",
  "Rice Flour": "Pirinç Unu",
  "Rice Noodles": "Pirinç Eriştesi",
  "Rice Vinegar": "Pirinç Sirkesi",
  Ricotta: "Ricotta Peyniri",
  Rocket: "Roka",
  "Rolled Oats": "Yulaf Ezmesi",
  Rosemary: "Biberiye",
  Rum: "Rom",
  Saffron: "Safran",
  Sage: "Adaçayı",
  Salmon: "Somon",
  Salsa: "Salsa Sosu",
  Salt: "Tuz",
  Sardines: "Sardalya",
  Sausages: "Sosis",
  Scallions: "Taze Soğan",
  "Sea Bass": "Levrek",
  "Sea Salt": "Deniz Tuzu",
  "Self-raising Flour": "Kendinden Kabarmalı Un",
  "Semi-skimmed Milk": "Yarım Yağlı Süt",
  Semolina: "İrmik",
  "Sesame Seed": "Susam",
  "Sesame Seed Oil": "Susam Yağı",
  Shallots: "Küçük Soğan (arpacık)",
  Sherry: "Şeri Şarabı",
  Shrimp: "Karides",
  "Single Cream": "Krema (sıvı)",
  "Smoked Ham": "Füme Jambon",
  "Smoked Paprika": "Füme Kırmızı Biber",
  "Smoked Salmon": "Füme Somon",
  "Snow Peas": "Taze Bezelye (fasulye tipi)",
  "Soda Water": "Soda",
  "Sour Cream": "Ekşi Krema",
  "Soy Sauce": "Soya Sosu",
  Spaghetti: "Spagetti",
  Spinach: "Ispanak",
  "Split Peas": "Bezelye (kabuksuz)",
  "Spring Onions": "Taze Soğan",
  Squash: "Kabak (squash)",
  Squid: "Kalamar",
  "Star Anise": "Yıldız Anason",
  "Stilton Cheese": "Stilton Peyniri",
  "Strawberries": "Çilek",
  "Strong White Flour": "Kuvvetli Beyaz Un",
  Sugar: "Şeker",
  Sultanas: "Kuru Üzüm (çekirdeksiz)",
  Sumac: "Sumak",
  "Sun-Dried Tomatoes": "Kurutulmuş Domates",
  "Sunflower Oil": "Ayçiçek Yağı",
  Swede: "Şalgam (İsveç şalgamı)",
  "Sweet Potatoes": "Tatlı Patates",
  Sweetcorn: "Mısır",
  "Sweetened Condensed Milk": "Şekerli Yoğunlaştırılmış Süt",
  "Swiss Cheese": "İsviçre Peyniri (Emmental)",
  "Tabasco Sauce": "Acı Sos (Tabasco)",
  Tahini: "Tahin",
  Tarragon: "Tarhun",
  Thyme: "Kekik",
  "Tiger Prawns": "Kaplan Karidesi",
  Toast: "Tost Ekmeği",
  Tofu: "Tofu",
  Tomato: "Domates",
  "Tomato Ketchup": "Ketçap",
  "Tomato Puree": "Domates Salçası",
  "Tomato Sauce": "Domates Sosu",
  Tomatoes: "Domates",
  Tortillas: "Tortilla",
  Treacle: "Şeker Pekmezi",
  Tripe: "İşkembe",
  Trout: "Alabalık",
  Tuna: "Ton Balığı",
  Turkey: "Hindi",
  "Turkey Mince": "Hindi Kıyma",
  Turmeric: "Zerdeçal",
  Turnips: "Şalgam",
  Vanilla: "Vanilya",
  "Vanilla Extract": "Vanilya Özütü",
  Veal: "Dana Eti (buzağı)",
  "Vegetable Oil": "Bitkisel Yağ",
  "Vegetable Stock": "Sebze Suyu",
  Vinegar: "Sirke",
  Walnuts: "Ceviz",
  "Warm Water": "Ilık Su",
  Water: "Su",
  "Whipping Cream": "Krema (çırpılabilir)",
  "White Wine": "Beyaz Şarap",
  "White Wine Vinegar": "Beyaz Şarap Sirkesi",
  "Whole Milk": "Tam Yağlı Süt",
  "Worcestershire Sauce": "Worcestershire Sosu",
  Yeast: "Maya",
  "Yellow Onion": "Sarı Soğan",
  "Yellow Pepper": "Sarı Biber",
  Yogurt: "Yoğurt",
  Zucchini: "Kabak",
  manchego: "Manchego Peyniri",
};

export function getIngredientLabel(name: string): string {
  return INGREDIENT_LABELS_TR[name] ?? name;
}
